//LISA-GALORE!
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ambush")
print("variants: night")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(15)
COM_BufInsertText(mo,"tunes ambush")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ambushnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6329)
COM_BufInsertText(mo,"tunes ambush")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "arrow")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6158)
COM_BufAddText(mo,"tunes arrow")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "baby")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(2383)
COM_BufAddText(mo,"tunes baby")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "babyslums")
print("variants: slums,jungle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes BABY")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "babyjungle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes BABY")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "band")
print("variants: sunset,jungle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1)
COM_BufAddText(mo,"tunes BAND")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bandsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6238)
COM_BufAddText(mo,"tunes BAND")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bandnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6983)
COM_BufAddText(mo,"tunes BAND")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hearts")
S_StartSound(mo, sfx_dstrcr)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
P_SwitchWeather(4)
COM_BufAddText(mo,"tunes HEARTS")
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "broken")
print("variants: BROKEN")
S_StartSound(mo, sfx_litng4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6349)
P_SwitchWeather(4)
COM_BufAddText(mo,"tunes BROKEH")
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "BROKEN")
print("variants: DARK,DARKER,DARKEST")
S_StartSound(mo, sfx_litng4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6349)
P_SwitchWeather(4)
COM_BufAddText(mo,"tunes BROKEN")
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "BROKENDARK")
S_StartSound(mo, sfx_litng4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
P_SwitchWeather(4)
COM_BufAddText(mo,"tunes BROKEN")
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "BROKENDARKER")
S_StartSound(mo, sfx_litng4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
P_SwitchWeather(4)
COM_BufAddText(mo,"tunes BROKEN")
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "BROKENDARKEST")
S_StartSound(mo, sfx_litng4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
P_SwitchWeather(4)
COM_BufAddText(mo,"tunes BROKEN")
P_FadeLight(65535, 125, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bath")
print("variants: BATH")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6199)
COM_BufAddText(mo,"tunes BATH")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "BATH")
S_StartSound(mo, sfx_spsmsh)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6315)
P_ElementalFire(player,true)
COM_BufAddText(mo,"tunes ANGRY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "blood")
print("variants: angry,hell,home,summer,arnold,cave,static,jungle,bile,land,city,rust")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6233)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodangry")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6297)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodhell")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4049)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodhome")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodsummer")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6284)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodarnold")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6282)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodcave")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodstatic")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4033)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodjungle")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodbile")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6296)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodland")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodcity")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodrust")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4119)
COM_BufAddText(mo,"tunes BFS")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "cometh")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6315)
COM_BufAddText(mo,"tunes BIGGAL")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SUNSET")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6324)
COM_BufAddText(mo,"tunes BIKE")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bile")
print("variants: BILE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6296)
COM_BufAddText(mo,"tunes BILE")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "BILE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes BILE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rising")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6390)
COM_BufAddText(mo,"tunes BLODM")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "casette")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes BLUES")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boogie")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes BOOGIE")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boy")
print("variants: night,city[sunset,night],green[sunset,night],summer,sand[sunset]")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6317)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boycity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6333)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boycitysunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6334)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boycitynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6375)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6318)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boygreen")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boygreensunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6238)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)
	
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boygreennight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6983)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boysummer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boysand")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(13)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boysandsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6286)
COM_BufAddText(mo,"tunes BOY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "AMY")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6321)
COM_BufAddText(mo,"tunes BUDDY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "HEARTBURN")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6325)
COM_BufAddText(mo,"tunes BURNFH")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "goodbye")
print("variants: sunset,night,lester,moon,GOODBYE")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(2383)
COM_BufAddText(mo,"tunes BYBABY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "goodbyesunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6316)
COM_BufAddText(mo,"tunes BYBABY")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "goodbyenight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6325)
COM_BufAddText(mo,"tunes BYBABY")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "goodbyelester")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6984)
COM_BufAddText(mo,"tunes BYBABY")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "goodbyemoon")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6267)
COM_BufAddText(mo,"tunes BYBABY")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GOODBYE")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(57)
COM_BufAddText(mo,"tunes BYE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "cherry")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6326)
COM_BufAddText(mo,"tunes CHERRY")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "creep")
print("variants: black,cave,CREEP")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6281)
COM_BufAddText(mo,"tunes CRPDSM")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "creepblack")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes CRPDSM")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "creepcave")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes CRPDSM")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "CREEP")
print("variants: BLACK,CAVE")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6281)
COM_BufAddText(mo,"tunes CREEP")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "CREEPBLACK")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes CREEP")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "CREEPCAVE")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes CREEP")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "dad")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6289)
COM_BufAddText(mo,"tunes DAD")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evil")
print("variants: sunset,night,city[sunset,night],industry,hell,summer,angry,home,cave,jungle,lester,bile,land,lone,EVIL")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(16)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilcity")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilcitysunset")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6383)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilcitynight")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6375)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilindustry")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4143)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilsunset")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(15)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilnight")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6329)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilhell")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4049)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilsummer")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilangry")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6297)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilhome")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilcave")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "eviljungle")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 210, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evillester")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6984)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilbile")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6296)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evilland")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "evillone")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(11)
COM_BufAddText(mo,"tunes EVIL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVIL")
print("variants: SUNSET,NIGHT,CITY[SUNSET,NIGHT],INDUSTRY,HELL,SUMMER,ANGRY,HOME,CAVE,JUNGLE,LESTER,BILE,LAND,LONE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(16)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILCITY")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILCITYSUNSET")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6383)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILCITYNIGHT")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6375)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILSUNSET")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(15)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILNIGHT")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6329)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILINDUSTRY")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4143)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILHELL")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4049)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILSUMMER")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILANGRY")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6297)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILHOME")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILCAVE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILJUNGLE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILLESTER")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6984)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILBILE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6296)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILLAND")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EVILLONE")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(11)
COM_BufAddText(mo,"tunes HART")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "fish")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6201)
COM_BufAddText(mo,"tunes FISH")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "trash")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6212)
COM_BufAddText(mo,"tunes GBDAY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "trashday")
print("variants: sunset,night")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6230)
COM_BufAddText(mo,"tunes GBDAY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "trashsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6229)
COM_BufAddText(mo,"tunes GBDAY")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "trashnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6361)
COM_BufAddText(mo,"tunes GBDAY")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "god")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes GODC")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "groove")
print("variants: blowout,special,space,story")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6201)
COM_BufAddText(mo,"tunes GROOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "grooveblowout")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes GROOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "groovespecial")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6214)
COM_BufAddText(mo,"tunes GROOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "groovespace")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6391)
COM_BufAddText(mo,"tunes GROOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "groovestory")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6199)
COM_BufAddText(mo,"tunes GROOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hair")
print("variants: HAIR")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6237)
COM_BufAddText(mo,"tunes HAIR")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "stand")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6296)
COM_BufAddText(mo,"tunes LLBLSV")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovely")
print("variants: LOVELY")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6324)
COM_BufAddText(mo,"tunes LOVELY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "LOVELY")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(15)
COM_BufAddText(mo,"tunes HARTSO")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bug")
print("variants: day,sunset,sunset,mystic,summer,fog,marble,aether")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6245)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugmystic")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6380)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugsummer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugslums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugfog")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6290)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugday")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(5)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(3)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6222)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugmarble")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6261)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bugaether")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(40)
COM_BufAddText(mo,"tunes HTCB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highway")
print("variants: sunset,night,mystic,spring,city[sunset,night],factory,forest[sunset,night],aether,slums,summer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaymystic")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6380)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayspring")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6332)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaycity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6333)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaycitysunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6383)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaycitynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6375)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayfactory")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6338)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayforest")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayforestsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6389)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayforestnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6370)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaysunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6238)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6983)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayaether")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(40)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwayslums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "highwaysummer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes HIGHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintz")
print("variants: sunset,night,marble,slums,forest[sunset,night]")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(2383)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintzmarble")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6261)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintzslums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintzsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6388)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintznight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6367)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintzforest")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintzforestsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6389)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hintzforestnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6370)
COM_BufAddText(mo,"tunes HINTZ")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "homeland")
print("variants: hills,summer,blood,trash,marble")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6204)
COM_BufAddText(mo,"tunes HUSSLE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "homelandhills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6234)
COM_BufAddText(mo,"tunes HUSSLE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "homelandsummer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes HUSSLE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "homelandblood")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6284)
COM_BufAddText(mo,"tunes HUSSLE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "homelandtrash")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6212)
COM_BufAddText(mo,"tunes HUSSLE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "homelandmarble")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6261)
COM_BufAddText(mo,"tunes HUSSLE")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "heartburn")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(18)
COM_BufAddText(mo,"tunes HARBUR")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylab")
print("variants: day,sunset,night,techno,polluted,trash,inside")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6297)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)


addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabday")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(5)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(3)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6222)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabtechno")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6338)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabpolluted")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6327)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabtrash")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6212)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joylabinside")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6374)
COM_BufAddText(mo,"tunes JOYLAB")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joyboy")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes JOYBOY")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "joyboycave")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes JOYBOY")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "run")
print("RUN")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(33)
COM_BufAddText(mo,"tunes JUSRUN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "RUN")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(34)
COM_BufAddText(mo,"tunes JRUN")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "kegger")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6320)
COM_BufAddText(mo,"tunes KEGGER")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "land")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes LAND")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lando")
print("variants: sunset,night,mystic,spring,summer,slums,fog,factory,factory[day,sunset,night],industry,aether,marble")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6377)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landomystic")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6380)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landospring")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6332)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landosummer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landoslums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landofog")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6290)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landofactory")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6338)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landofactoryday")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(5)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landofactorysunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(3)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landoindustry")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4143)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landofactorynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6222)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landosunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6378)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landonight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6379)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landomarble")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6261)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "landoaether")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(40)
COM_BufAddText(mo,"tunes LANDO")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "weird")
print("variants: arnold,hell")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(57)
COM_BufAddText(mo,"tunes LCBHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "weirdarnold")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6282)
COM_BufAddText(mo,"tunes LCBHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "weirdhell")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4049)
COM_BufAddText(mo,"tunes LCBHW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lester")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6984)
COM_BufAddText(mo,"tunes LESTER")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lone")
print("variants: snow,snownight,weed,home,cave,jungle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(11)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lonesnow")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(55)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(2)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lonesnownight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6278)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(2)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "loneweed")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(50)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lonehome")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lonecave")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lonejungle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes LONE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "love")
print("variants: desert,cave,moon,rust,angry,trash,dark,red,blowout")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6385)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovedesert")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6387)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovecave")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovemoon")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6267)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "loverust")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4119)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "loveangry")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6297)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovemist")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6410)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "loveblowout")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovedark")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lovered")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6233)
COM_BufAddText(mo,"tunes LOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "STROLL")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes STROLL")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "stroll")
print("STROLL")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes LTHDSR")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "march")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6283)
COM_BufAddText(mo,"tunes MARCH")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "merica")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6269)
COM_BufAddText(mo,"tunes MERICA")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "MERICA")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6330)
COM_BufAddText(mo,"tunes USA")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "blockland")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6330)
COM_BufAddText(mo,"tunes BLOCK")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "moist")
print("variants: space,night,cave")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6281)
COM_BufAddText(mo,"tunes MOIST")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "moistspace")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6391)
COM_BufAddText(mo,"tunes MOIST")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "moistnight")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6341)
COM_BufAddText(mo,"tunes MOIST")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "moistcave")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes MOIST")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "swamp")
print("variants: plains,forest,")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6230)
COM_BufAddText(mo,"tunes MUDDY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "swampplains")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6353)
COM_BufAddText(mo,"tunes MUDDY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "swampforest")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes MUDDY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "story")
print("night,green,greensunset,greennight,summer,home")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6225)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6263)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storysunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(159)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storygreen")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storygreensunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6238)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storygreennight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6983)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storysummer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "storyhome")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(129)
COM_BufAddText(mo,"tunes NERN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "death")
print("variants: rust,blowout,moon,hell,red,dark,hill,scrap,mountain")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6385)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathrust")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4119)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathblowout")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathmoon")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6256)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathhell")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4049)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathred")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6287)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathdark")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathhill")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4113)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathscrap")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6231)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "deathmountain")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6269)
COM_BufAddText(mo,"tunes PEACE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "raid")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(27)
COM_BufAddText(mo,"tunes RAID")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampage")
print("variants: rust,blowout,moon,hell,red,dark,hill,scrap,mountain")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6280)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 125, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampagemouth")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6354)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 125, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampagerust")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4119)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 125, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampagehell")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4049)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampagecave")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 120, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampagejungle")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rampagehome")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes RAMPAG")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "roll")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1025)
COM_BufAddText(mo,"tunes ROLL")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shanty")
print("variants: night,underwater")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6272)
COM_BufAddText(mo,"tunes SHANTY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shantyunderwater")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6384)
COM_BufAddText(mo,"tunes SHANTY")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shantynight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6371)
COM_BufAddText(mo,"tunes SHANTY")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shiver")
print("variants: glacier,night")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(30)
COM_BufAddText(mo,"tunes LOVER")
P_SwitchWeather(2)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shiverglacier")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6246)
COM_BufAddText(mo,"tunes LOVER")
P_SwitchWeather(2)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shivernight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6278)
COM_BufAddText(mo,"tunes LOVER")
P_SwitchWeather(2)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SHIVER")
print("variants: GLACIER,NIGHT")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(30)
COM_BufAddText(mo,"tunes SHIVER")
P_SwitchWeather(2)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SHIVERGLACIER")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6246)
COM_BufAddText(mo,"tunes SHIVER")
P_SwitchWeather(2)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SHIVERNIGHT")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6278)
COM_BufAddText(mo,"tunes SHIVER")
P_SwitchWeather(2)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "skin")
print("variants: rust,mouth")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6212)
COM_BufAddText(mo,"tunes SOFT")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "skinrust")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4119)
COM_BufAddText(mo,"tunes SOFT")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "skinmouth")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6354)
COM_BufAddText(mo,"tunes SOFT")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "666")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6323)
COM_BufAddText(mo,"tunes SSSKCD")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "summer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6285)
COM_BufAddText(mo,"tunes SUMMER")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "blowout")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes BLOW")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ollie")
print("variants: day,sunset,night,polluted,techno,inside,trash")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6234)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ollieday")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(5)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "olliesunset")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(3)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ollienight")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6222)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ollietechno")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6338)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "olliepolluted")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6327)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ollieinside")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6374)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ollietrash")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6212)
COM_BufAddText(mo,"tunes OLLIE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "glitter")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes GLITTR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "wonder")
S_StartSound(mo, sfx_kc4b)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4185)
COM_BufAddText(mo,"tunes WONDER")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "soft")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6328)
COM_BufAddText(mo,"tunes SOFTH")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "arnold")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6282)
COM_BufAddText(mo,"tunes ARNLAN")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "firebird")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6283)
COM_BufAddText(mo,"tunes FIREZN")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "FIREBIRD")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6283)
COM_BufAddText(mo,"tunes ARNDTH")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "snake")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6283)
COM_BufAddText(mo,"tunes UROBOR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SWAMP")
print("variants: MUSHROOM")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6279)
COM_BufAddText(mo,"tunes SWAMP")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SWAMPMUSHROOM")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6331)
COM_BufAddText(mo,"tunes SWAMP")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "voices")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6247)
COM_BufAddText(mo,"tunes VOICES")
P_SwitchWeather(4)
P_FadeLight(65535, 1750, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "heck")
print("variants: HECK")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1027)
COM_BufAddText(mo,"tunes WCTH")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "HECK")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes WCTH")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hailton")
print("variants: sunset,night")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(16)
COM_BufAddText(mo,"tunes HAILTN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hailtonsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(15)
COM_BufAddText(mo,"tunes HAILTN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hailtonnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6329)
COM_BufAddText(mo,"tunes HAILTN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "fear")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6350)
COM_BufAddText(mo,"tunes FEAR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "eddy")
print("variants: EDDY")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6358)
COM_BufAddText(mo,"tunes EDYLED")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "EDDY")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6323)
COM_BufAddText(mo,"tunes AIREDY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "eyes")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6386)
COM_BufAddText(mo,"tunes AIMEYE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "twist")
print("variants: TWIST")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes THTWST")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "TWIST")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6213)
COM_BufAddText(mo,"tunes TWISTR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "icecube")
print("variants: ICECUBE")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6363)
COM_BufAddText(mo,"tunes ICECUB")
P_SwitchWeather(2)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ICECUBE")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(107)
COM_BufAddText(mo,"tunes ICECUB")
P_SwitchWeather(2)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hans")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6385)
COM_BufAddText(mo,"tunes DSHANS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "waste")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6368)
COM_BufAddText(mo,"tunes WASTOS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "king")
print("variants: KING")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6175)
COM_BufAddText(mo,"tunes KINGDIC")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "KING")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6345)
COM_BufAddText(mo,"tunes MONRCH")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "wrong")
print("variants: cave,slums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(570)
COM_BufAddText(mo,"tunes WRONG")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "wrongcave")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes WRONG")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "wrongslums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes WRONG")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "simmer")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6362)
COM_BufAddText(mo,"tunes SIMMER")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "sireen")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6206)
COM_BufAddText(mo,"tunes SIREEN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "feel")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4185)
COM_BufAddText(mo,"tunes TFEEOH")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "sacrifice")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6316)
COM_BufAddText(mo,"tunes SACRIF")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "steel")
print("variants: city,land")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6212)
COM_BufAddText(mo,"tunes HOTMTL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "steelcity")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes HOTMTL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "steelland")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes HOTMTL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "gohome")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6316)
COM_BufAddText(mo,"tunes GOHOME")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "giveup")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6290)
COM_BufAddText(mo,"tunes GIVEUP")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bracket")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6294)
COM_BufAddText(mo,"tunes BRACKT")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "scared")
print("variants: SCARED")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6358)
COM_BufAddText(mo,"tunes SCARED")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SCARED")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6326)
COM_BufAddText(mo,"tunes LESBIA")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "HAIR")
S_StartSound(mo, sfx_dsecho)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6237)
COM_BufAddText(mo,"tunes MNHAIR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "gangam")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6348)
COM_BufAddText(mo,"tunes SANSGA")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lingers") or (msg == "linger")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6416)
COM_BufAddText(mo,"tunes LINGER")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)


addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "call")
COM_BufAddText(mo,"tunes BIGBOY")
end
end)