//Mushroom Kingdom stuff! Go crazy! Mario 76, My Uncle Mario, Mario VS The IRS, Mario and the secret mushrooms, Mario & Sonic at the F-City, Mario-
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mushroom")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(31)
COM_BufAddText(mo,"tunes MARIO1")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "pipes")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8001)
COM_BufAddText(mo,"tunes MARIO2")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "cavern")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6168)
COM_BufAddText(mo,"tunes CAVEDU")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "iceberg")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6163)
COM_BufAddText(mo,"tunes SNOMOU")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "holt")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6169)
COM_BufAddText(mo,"tunes ROMANC")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "water")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6162)
COM_BufAddText(mo,"tunes PORTIS")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "sky")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6170)
COM_BufAddText(mo,"tunes NONINE")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "sail")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6176)
COM_BufAddText(mo,"tunes SWEDSI")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "lava")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6172)
COM_BufAddText(mo,"tunes LADWEL")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "castle")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6166)
COM_BufAddText(mo,"tunes SACBLO")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "CASTLE")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6271)
COM_BufAddText(mo,"tunes DEREIN")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ashes")
S_StartSound(mo, sfx_mario4)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6171)
COM_BufAddText(mo,"tunes GEARS")
P_SwitchWeather(0)
P_FadeLight(65535, 220, 2)
end
end)