//LEWD LEAF LAND!!! WOOHOOOOO I LOVE MOLLYYYYYY (AND I LOVE MY BROTHER SO MUCH ;D)
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "molly" or msg == "sexy")
S_StartSound(mo, sfx_dslewd)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4627)
COM_BufAddText(mo,"tunes SEXYDN")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "valley" or msg == "mobius")
S_StartSound(mo, sfx_dslewd)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4627)
COM_BufAddText(mo,"tunes VALAND")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shiyou" or msg == "sex")
S_StartSound(mo, sfx_dslewd)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4627)
COM_BufAddText(mo,"tunes SHIYOU")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shrooms")
S_StartSound(mo, sfx_dslewd)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6444)
COM_BufAddText(mo,"tunes CANSEE")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shroomsbig")
S_StartSound(mo, sfx_dslewd)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6446)
COM_BufAddText(mo,"tunes CANSEE")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "shroomscave")
S_StartSound(mo, sfx_dslewd)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6445)
COM_BufAddText(mo,"tunes CANSEE")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)