//Songs from Yume Nikki, 2kki and .Flow. Character themes are EXCLUDED here though! Dream on.
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "block")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6290)
COM_BufAddText(mo,"tunes YNCUBE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "blockslums")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6180)
COM_BufAddText(mo,"tunes YNCUBE")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "DARK")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6275)
COM_BufAddText(mo,"tunes YNDRKW")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "DARKNIGHT")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(99)
COM_BufAddText(mo,"tunes YNDRKW")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woods")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes YNWODA")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woodsjungle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(64)
COM_BufAddText(mo,"tunes YNWODA")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6410)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 120, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candleice")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(107)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candlehome")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candlepalace")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(132)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candlecave")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(7)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candlemountain")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6269)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "candlehills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6385)
COM_BufAddText(mo,"tunes YNCNDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mars")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6202)
COM_BufAddText(mo,"tunes MARTU")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "marscity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6190)
COM_BufAddText(mo,"tunes MARTU")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "marssunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(59)
COM_BufAddText(mo,"tunes MARTU")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "marsnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6335)
COM_BufAddText(mo,"tunes MARTU")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "marslester")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6984)
COM_BufAddText(mo,"tunes MARTU")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "marshills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6234)
COM_BufAddText(mo,"tunes MARTU")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "spring")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6380)
COM_BufAddText(mo,"tunes YNSPRN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "world")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6336)
COM_BufAddText(mo,"tunes YNWOLD")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "snowy")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6363)
COM_BufAddText(mo,"tunes YNSNOW")
P_SwitchWeather(2)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "snowyglacier")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6246)
COM_BufAddText(mo,"tunes YNSNOW")
P_SwitchWeather(2)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "nether")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6357)
COM_BufAddText(mo,"tunes YNHELL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "netherhills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6360)
COM_BufAddText(mo,"tunes YNHELL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "end")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6197)
COM_BufAddText(mo,"tunes YNEND")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mural")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6223)
COM_BufAddText(mo,"tunes YNMURL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "muralday")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6240)
COM_BufAddText(mo,"tunes YNMURL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "muralsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6189)
COM_BufAddText(mo,"tunes YNMURL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "muralnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6244)
COM_BufAddText(mo,"tunes YNMURL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "vision")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8874)
COM_BufAddText(mo,"tunes YNDREM")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "monke")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4185)
COM_BufAddText(mo,"tunes YNMONO")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "famicom")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6199)
COM_BufAddText(mo,"tunes YNFAMI")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "famicomfish")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6201)
COM_BufAddText(mo,"tunes YNFAMI")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "famicomspace")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6188)
COM_BufAddText(mo,"tunes YNFAMI")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "party")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1992)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partybeach")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6272)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partybeachsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6342)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partyhill")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4073)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partyspring")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6332)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partygreen")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(1)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partygreensunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6238)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "partygreennight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6983)
COM_BufAddText(mo,"tunes YNPRTY")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barracks")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6395)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barrackstown")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6392)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barrackstownnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6403)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barracksland")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barrackscity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barrackshills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6385)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "barrackshill")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4113)
COM_BufAddText(mo,"tunes YNBRKS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mill")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6338)
COM_BufAddText(mo,"tunes YNMILL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "millinside")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6374)
COM_BufAddText(mo,"tunes YNMILL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "millday")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(5)
COM_BufAddText(mo,"tunes YNMILL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "millsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(3)
COM_BufAddText(mo,"tunes YNMILL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "millnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6222)
COM_BufAddText(mo,"tunes YNMILL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "witch")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6245)
COM_BufAddText(mo,"tunes YNBRUJ")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "witchsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6393)
COM_BufAddText(mo,"tunes YNBRUJ")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "WOODS")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes YMBOSQ")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "PINK")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6240)
COM_BufAddText(mo,"tunes YNPINK")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "PINKNIGHT")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6244)
COM_BufAddText(mo,"tunes YNPINK")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "check")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4132)
COM_BufAddText(mo,"tunes YMCHCK")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "number")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6395)
COM_BufAddText(mo,"tunes YNUMBR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "numberindustry")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4143)
COM_BufAddText(mo,"tunes YNUMBR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "numbercity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes YNUMBR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "numberland")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes YNUMBR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "numbertown")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6392)
COM_BufAddText(mo,"tunes YNUMBR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "numbertownnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6403)
COM_BufAddText(mo,"tunes YNUMBR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "light")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6275)
COM_BufAddText(mo,"tunes YNLTOF")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "LIGHT")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(9109)
COM_BufAddText(mo,"tunes YNLTON")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "puddle")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6396)
COM_BufAddText(mo,"tunes YNPUDL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "dream")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6194)
COM_BufAddText(mo,"tunes YNDREA")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "ghost")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6357)
COM_BufAddText(mo,"tunes YNGOST")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "stair")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6397)
COM_BufAddText(mo,"tunes YNESCA")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "garden")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6398)
COM_BufAddText(mo,"tunes YNGRDN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "gardenhills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6399)
COM_BufAddText(mo,"tunes YNGRDN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "glitch")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4139)
COM_BufAddText(mo,"tunes YNGLIT")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woodland")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes YNWODL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woodlandland")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4115)
COM_BufAddText(mo,"tunes YNWODL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woodlandcity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6382)
COM_BufAddText(mo,"tunes YNWODL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woodlandtown")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6392)
COM_BufAddText(mo,"tunes YNWODL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "woodlandtownnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6403)
COM_BufAddText(mo,"tunes YNWODL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mall")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6222)
COM_BufAddText(mo,"tunes YNMALL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mallbridge")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6397)
COM_BufAddText(mo,"tunes YNMALL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mallindustry")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4143)
COM_BufAddText(mo,"tunes YNMALL")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "neon")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6189)
COM_BufAddText(mo,"tunes YNNEON")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "desert")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6388)
COM_BufAddText(mo,"tunes YNDSRT")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "desertforest")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6389)
COM_BufAddText(mo,"tunes YNDSRT")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "desertnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6387)
COM_BufAddText(mo,"tunes YNDSRT")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "sleep")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6270)
COM_BufAddText(mo,"tunes YNSLEP")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "eyeball")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6400)
COM_BufAddText(mo,"tunes YNOJOS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "underground")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(570)
COM_BufAddText(mo,"tunes YNUNDR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "undergroundindustry")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4143)
COM_BufAddText(mo,"tunes YNUNDR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "undergroundscrap")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6231)
COM_BufAddText(mo,"tunes YNUNDR")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "space")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6401)
COM_BufAddText(mo,"tunes YNSPAC")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "MARS")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6402)
COM_BufAddText(mo,"tunes YNMARS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "MARSCITY")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6190)
COM_BufAddText(mo,"tunes YNMARS")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "somewhere")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6337)
COM_BufAddText(mo,"tunes SOMWHR")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "terminal")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4119)
COM_BufAddText(mo,"tunes DFTERM")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "underwater")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6193)
COM_BufAddText(mo,"tunes DFWATR")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "underwaternight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6384)
COM_BufAddText(mo,"tunes DFWATR")
P_SwitchWeather(4)
P_FadeLight(65535, 175, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "school")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6416)
COM_BufAddText(mo,"tunes DFSCOL")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "street")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6415)
COM_BufAddText(mo,"tunes DFSTRT")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "path")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6424)
COM_BufAddText(mo,"tunes DFPATH")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hospital") or (msg == "corrupted")
player.corrupted=1
S_StartSound(mo, sfx_kc6d)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6413)
COM_BufAddText(mo,"tunes DFMINT")
P_SwitchWeather(1)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "body")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6427)
COM_BufAddText(mo,"tunes DFBODY")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bodyred")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6428)
COM_BufAddText(mo,"tunes DFBODY")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bodytemple")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6429)
COM_BufAddText(mo,"tunes DFBODY")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "way")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8018)
COM_BufAddText(mo,"tunes DFISOP")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "waylife")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8050)
COM_BufAddText(mo,"tunes DFISOP")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SAFEROOM")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8082)
COM_BufAddText(mo,"tunes DFSFRM")
P_SwitchWeather(4)
P_FadeLight(65535, 155, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "overgrown")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6430)
COM_BufAddText(mo,"tunes DFOVRG")
P_SwitchWeather(4)
P_FadeLight(65535, 155, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "OVERGROWN")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8115)
COM_BufAddText(mo,"tunes DFOVRG")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "sugar") or (msg == "mansion")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6432)
COM_BufAddText(mo,"tunes DFSUGR")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "SUGAR") or (msg == "MANSION")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6431)
COM_BufAddText(mo,"tunes DFSUGR")
P_SwitchWeather(4)
P_FadeLight(65535, 170, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mouth")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6354)
COM_BufAddText(mo,"tunes DFMTH")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mouthflesh")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6428)
COM_BufAddText(mo,"tunes DFMTH")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "MOUTH")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6437)
COM_BufAddText(mo,"tunes DFDMTH")
P_SwitchWeather(4)
P_FadeLight(65535, 115, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "MOUTHFLESH")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8147)
COM_BufAddText(mo,"tunes DFDMTH")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "plant")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6433)
COM_BufAddText(mo,"tunes DFPLNT")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hotel")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6434)
COM_BufAddText(mo,"tunes DFLOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hotelbase")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6435)
COM_BufAddText(mo,"tunes DFLOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hotelspeedway")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6425)
COM_BufAddText(mo,"tunes DFLOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hotelcasino")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6319)
COM_BufAddText(mo,"tunes DFLOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "hotelcity")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6415)
COM_BufAddText(mo,"tunes DFLOVE")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "DREAM")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6203)
COM_BufAddText(mo,"tunes DFDREM")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bone")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6437)
COM_BufAddText(mo,"tunes DFBONE")
P_SwitchWeather(4)
P_FadeLight(65535, 110, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bonecave")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6416)
COM_BufAddText(mo,"tunes DFBONE")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bonered")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6233)
COM_BufAddText(mo,"tunes DFBONE")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bonetemple")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6429)
COM_BufAddText(mo,"tunes DFBONE")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "boneflames" or msg == "bonefire")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4523)
COM_BufAddText(mo,"tunes DFBONE")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "room")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes DFWHIT")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "roomruins")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6438)
COM_BufAddText(mo,"tunes DFWHIT")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "inside")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes DFINSD")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "insideruins")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6438)
COM_BufAddText(mo,"tunes DFINSD")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "eye")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6439)
COM_BufAddText(mo,"tunes DFRDAY")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "eyehills")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6440)
COM_BufAddText(mo,"tunes DFRDAY")
P_SwitchWeather(4)
P_FadeLight(65535, 140, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GARDEN")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6441)
COM_BufAddText(mo,"tunes DFGSTR")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GARDENINSIDE")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6374)
COM_BufAddText(mo,"tunes DFGSTR")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GARDENTOXIC")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6442)
COM_BufAddText(mo,"tunes DFGSTR")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "heart")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6244)
COM_BufAddText(mo,"tunes DFTNGL")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GHOST")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6443)
COM_BufAddText(mo,"tunes DFGOST")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GHOSTFLAMES")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8185)
COM_BufAddText(mo,"tunes DFGOST")
P_SwitchWeather(4)
P_FadeLight(65535, 135, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "GHOSTEYES")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(8193)
COM_BufAddText(mo,"tunes DFGOST")
P_SwitchWeather(4)
P_FadeLight(65535, 145, 2)
end
end)

addHook("ThinkFrame", function()
for player in players.iterate do
if (player.pflags & PF_FINISHED) then
player.corrupted=0
end
if player.corrupted==1 then
if S_IdPlaying(sfx_litng1) or S_IdPlaying(sfx_litng2) or S_IdPlaying(sfx_litng3) or S_IdPlaying(sfx_litng4) or S_IdPlaying(sfx_athun1) or S_IdPlaying(sfx_athun2)-- thunder?
P_SetupLevelSky(6414)
--print("on!") -- beep if yes
else
P_SetupLevelSky(6413)
--print("off!") -- beep if no
end
end
end
end)

