//Hotline Miami MY BELOVEDDD
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "animal")
S_StartSound(mo, sfx_dspump)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(98)
COM_BufAddText(mo,"tunes ANIMAL")
P_SwitchWeather(4)
P_FadeLight(65535, 165, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "massacre")
S_StartSound(mo, sfx_dslisa)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes MASSACRE")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "riot")
S_StartSound(mo, sfx_dsbrek)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6299)
COM_BufAddText(mo,"tunes RIOT")
P_SwitchWeather(4)
P_FadeLight(65535, 210, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "miami")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4)
COM_BufAddText(mo,"tunes MIAMI")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "beard")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(53)
COM_BufAddText(mo,"tunes BEARD")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "rust")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(56)
COM_BufAddText(mo,"tunes RUST")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "morning")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(4)
COM_BufAddText(mo,"tunes MORNIN")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "around")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(129)
COM_BufAddText(mo,"tunes AROUND")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "aroundnight")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(302)
COM_BufAddText(mo,"tunes AROUND")
P_SwitchWeather(4)
P_FadeLight(65535, 190, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "aroundday")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(128)
COM_BufAddText(mo,"tunes AROUND")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "aroundsunset")
S_StartSound(mo, sfx_dsitem)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(127)
COM_BufAddText(mo,"tunes AROUND")
P_SwitchWeather(4)
P_FadeLight(65535, 210, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "bloodline")
S_StartSound(mo, sfx_dspump)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6341)
COM_BufAddText(mo,"tunes BLOODL")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "fans")
S_StartSound(mo, sfx_dspump)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(98)
COM_BufAddText(mo,"tunes FANS")
P_SwitchWeather(4)
P_FadeLight(65535, 160, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "mobster")
S_StartSound(mo, sfx_dspump)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(98)
COM_BufAddText(mo,"tunes MOBSTER")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "safehouse")
S_StartSound(mo, sfx_dspump)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6)
COM_BufAddText(mo,"tunes SAFEHS")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "disco")
S_StartSound(mo, sfx_dspump)
P_SetSkyboxMobj(mo)
COM_BufAddText(mo,"tunes DISCO")
P_SetupLevelSky(9)
P_SwitchWeather(4)
P_FadeLight(65535, 240, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "angry")
S_StartSound(mo, sfx_spsmsh)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6297)
P_ElementalFire(player,true)
COM_BufAddText(mo,"tunes TURF")
P_SwitchWeather(4)
P_FadeLight(65535, 220, 2)
end
end)
