//Red stuff (NES GODZILLA)
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "heat")
S_StartSound(mo, sfx_rocks2)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6406)
COM_BufAddText(mo,"tunes HEAT")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "toxic")
S_StartSound(mo, sfx_rocks2)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6421)
COM_BufAddText(mo,"tunes TOXINA")
P_SwitchWeather(4)
P_FadeLight(65535, 150, 2)
end
end)
