//BFE Stuff
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "luna")
S_StartSound(mo, sfx_kc6d)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6325)
COM_BufAddText(mo,"tunes LUNAPP")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "everfree")
S_StartSound(mo, sfx_kc6d)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6322)
COM_BufAddText(mo,"tunes EVERFR")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "acres")
S_StartSound(mo, sfx_kc6d)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6251)
COM_BufAddText(mo,"tunes ACRES")
P_SwitchWeather(4)
P_FadeLight(65535, 200, 2)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "NIGHT")
S_StartSound(mo, sfx_kc6d)
P_SetSkyboxMobj(mo)
P_SetupLevelSky(6270)
COM_BufAddText(mo,"tunes BFENIG")
P_SwitchWeather(4)
P_FadeLight(65535, 180, 2)
end
end)

//Dreamy Rainbow
addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "calm")
P_FlashPal(player, PAL_WHITE, 8)
S_StartSound(mo, sfx_dsblip)
P_SetSkyboxMobj(mo)
P_DoPlayerPain(player, mo)
P_SetupLevelSky(6315)
COM_BufAddText(mo,"tunes CALM")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 1)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "dismay")
P_FlashPal(player, PAL_WHITE, 8)
S_StartSound(mo, sfx_dsblip)
P_SetSkyboxMobj(mo)
P_DoPlayerPain(player, mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes DISMAY")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 1)
end
end)

addHook("PlayerMsg", function(player, msgtype, target, msg)
if (msg == "dreamy")
P_FlashPal(player, PAL_WHITE, 8)
S_StartSound(mo, sfx_dsblip)
P_SetSkyboxMobj(mo)
P_DoPlayerPain(player, mo)
P_SetupLevelSky(6295)
COM_BufAddText(mo,"tunes DREAMY")
P_SwitchWeather(4)
P_FadeLight(65535, 130, 1)
end
end)